SCREEN_WIDTH = 288
SCREEN_HEIGHT = 512
FPS = 60
GRAVITY = 0.4

# Genetic Algorithm Parameters
NUM_GENERATION = 1000
NUM_INDIVIDUAL = 500
NUM_ELITE = 50
MUTATION_RATE = 0.3
MUTATION_STD = 0.25
NUM_CROSSOVER = NUM_INDIVIDUAL - NUM_ELITE

# Model Architecture
IN_DIM = 6
HIDDEN_1 = 8
OUT_DIM = 1

THRESHOLD = 0.5
