SCREEN_WIDTH = 288
SCREEN_HEIGHT = 512
FPS = 60
GRAVITY = 0.4

# Genetic Algorithm Parameters
NUM_GENERATION = 3
NUM_INDIVIDUAL = 3
NUM_ELITE = 4
MUTATION_RATE = 0.3
MUTATION_STD = 0.05
NUM_CROSSOVER = NUM_INDIVIDUAL - NUM_ELITE

# Model Architecture
IN_DIM = 4
HIDDEN_1 = 8
OUT_DIM = 1

THRESHOLD = 0.5
